### ISSUE TITLE
Not installable via Composer for Expressive v2

### ISSUE THREAD

**Issue by adamculp** [orasik/monolog-middleware#4]
Currently the dependency on "zendframework/zend-stratigility": "^1.2" prevents Composer from adding this to a Zend Expressive v2+ app. There is a different signature in version 2, so simply updating the composer.json may not do it. (haven't tested that)

If I get some down cycles I will try to do a PR, but not sure when/if that will happen soon.

**Comment by orasik** [comment]
I will need to update the code to be compatible with ZE 2 because the middleware interface itself was changed as you mentioned. I will work on that in the next coming 2 days and will keep you updated

**Comment by orasik** [comment]
@adamculp Try it now please. I have updated the middleware to be compatible with ZE2. I have tested it with skeleton ZE2 as well.

Cheers,
Oras

**Comment by adamculp** [comment]
Wow, thank you Oras, installed just fine now with the latest v 2.0.0 tag. Much appreciated.
