### ISSUE TITLE
Exception Logging in Zend Expressive 1

### ISSUE THREAD

**Issue by diego-betto** [orasik/monolog-middleware#6]
Hi, 

can you provide an example of how implement monolog-middleware for exception logging in zend expressive 1?

Thank you

**Comment by orasik** [comment]
Hi Diego,
Sorry for late reply. 
you need to require version `1.1.4`.

```
composer require oras/monolog-middleware:1.1.4
```
Then its the same steps from [documentation](https://github.com/orasik/monolog-middleware/blob/master/README.md)

Please let me know if this works for you.
